Repository storb-tech/storb, pull requests merged in 2025-04, with the labels that each got.

#67 Optimise piece downloads
  crates/storb_validator/src/download.rs
Labels: enhancement

#58 Optimize downloads and uploads
  crates/storb/src/cli/apikey_manager.rs
  crates/storb/src/cli/args.rs
  crates/storb/src/config.rs
  crates/storb/src/log.rs
  crates/storb_base/src/constants.rs
  crates/storb_base/src/lib.rs
  crates/storb_base/src/memory_db.rs
  crates/storb_base/src/piece.rs
  crates/storb_base/src/swarm/db.rs
  crates/storb_base/src/swarm/dht.rs
  crates/storb_base/src/swarm/models.rs
  crates/storb_base/src/sync.rs
  crates/storb_validator/src/apikey.rs
  crates/storb_validator/src/constants.rs
  crates/storb_validator/src/download.rs
  crates/storb_validator/src/lib.rs
  crates/storb_validator/src/routes.rs
  crates/storb_validator/src/upload.rs
  crates/storb_validator/src/utils.rs
  crates/storb_validator/src/validator.rs
  settings.toml.example
Labels: bug, enhancement

#81 chore: bump tokio to v1.44.2
  Cargo.lock
  Cargo.toml
Labels: dependencies

#95 DHT and API node rate limiting and more
  Cargo.lock
  Cargo.toml
  crates/storb_base/Cargo.toml
  crates/storb_base/src/constants.rs
  crates/storb_base/src/lib.rs
  crates/storb_base/src/swarm/db.rs
  crates/storb_base/src/swarm/dht.rs
  crates/storb_base/src/swarm/mod.rs
  crates/storb_base/src/swarm/peer_verifier.rs
  crates/storb_base/src/swarm/store.rs
  crates/storb_base/src/sync.rs
  crates/storb_miner/Cargo.toml
  crates/storb_miner/src/constants.rs
  crates/storb_miner/src/lib.rs
  crates/storb_miner/src/middleware.rs
  crates/storb_miner/src/miner.rs
  crates/storb_miner/src/routes.rs
  crates/storb_validator/Cargo.toml
  crates/storb_validator/src/constants.rs
  crates/storb_validator/src/download.rs
  crates/storb_validator/src/lib.rs
  crates/storb_validator/src/middleware.rs
  crates/storb_validator/src/routes.rs
  crates/storb_validator/src/scoring.rs
  crates/storb_validator/src/upload.rs
  crates/storb_validator/src/utils.rs
  crates/storb_validator/src/validator.rs
Labels: bug

#102 feat: concurrent challenges and better error handling
  crates/storb_validator/src/constants.rs
  crates/storb_validator/src/upload.rs
  crates/storb_validator/src/validator.rs
Labels: enhancement

#108 Basic OTel instrumentation
  Cargo.lock
  Cargo.toml
  crates/storb_base/src/lib.rs
  crates/storb_cli/Cargo.toml
  crates/storb_cli/src/cli/args.rs
  crates/storb_cli/src/cli/validator.rs
  crates/storb_cli/src/config.rs
  crates/storb_cli/src/log.rs
  crates/storb_cli/src/main.rs
  crates/storb_validator/Cargo.toml
  crates/storb_validator/src/lib.rs
  crates/storb_validator/src/validator.rs
  settings.toml.example
Labels: telemetry
